android github action build error
> Task :design:kaptGenerateStubsAlphaReleaseKotlin
w: Support for language version 2.0+ in kapt is in Alpha and must be enabled explicitly. Falling back to 1.9.

> Task :design:kaptAlphaReleaseKotlin
> Task :app:dataBindingMergeDependencyArtifactsAlphaRelease
> Task :app:dataBindingGenBaseClassesAlphaRelease
e: file:///home/runner/work/ClashMetaForAndroid/ClashMetaForAndroid/design/src/main/java/com/github/kr328/clash/design/adapter/ProxyAdapter.kt:39:14 Unresolved reference 'swapDataSet'.

> Task :design:compileAlphaReleaseKotlin FAILED

gradle/actions: Writing build results to /home/runner/work/_temp/.gradle-actions/build-results/__run_6-1787562410225.json
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':design:compileAlphaReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
219 actionable tasks: 219 executed
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 58s
Error: Process completed with exit code 1.

Kanban-Session: db6acf91-100c-4bce-88f4-c7edc4e7237f
Kanban-Card: c3ee682a-8475-4cbc-9383-f5b5dd8c865a
Co-authored-by: Cursor <cursoragent@cursor.com>